export const FETCH_POSTS = "FETCH_POSTS";
export const SET_POSTS = "SET_POSTS";
export const SET_LOADING_DATA = "SET_LOADING_DATA";

export const FETCH_COMMENTS_BY_ID = "FETCH_COMMENTS_BY_ID";
export const SET_COMMENTS_BY_ID = "SET_COMMENTS_BY_ID";
export const SET_LOADING_COMMENTS = "SET_LOADING_COMMENTS";

export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_POSTS = "SET_USER_POSTS";
export const SET_LOADING_USER_DATA = "SET_LOADING_USER_DATA";
export const SET_LOADING_USER_POSTS = "SET_LOADING_USER_POSTS";

export const SET_POSTS_ERROR = "SET_POSTS_ERROR";
export const SET_COMMENTS_ERROR = "SET_COMMENTS_ERROR";
export const SET_USER_POSTS_ERROR = "SET_USER_POSTS_ERROR";
export const SET_USER_DATA_ERROR = "SET_USER_DATA_ERROR";
